# Generated by Django 4.0.5 on 2022-06-29 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='selectedProduct_FK',
            field=models.ForeignKey(blank=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CartList', to='cart.selectedproduct'),
        ),
        migrations.AddField(
            model_name='selectedproduct',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
