# Generated by Django 4.0.5 on 2022-07-06 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='selectedProduct_FK',
            new_name='products',
        ),
    ]
