# Generated by Django 4.0.5 on 2022-06-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=30, null=True, unique=True)),
                ('firstname', models.CharField(max_length=30, null=True)),
                ('lastname', models.CharField(max_length=30, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='upload')),
                ('is_active', models.BooleanField(default=False, help_text=' Indique si cet utilisateur doit être considéré comme actif.')),
                ('is_admin', models.BooleanField(default=False, help_text=' Indique si cet utilisateur peut accéder au site d’administration === is_staff.')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
