# Generated by Django 4.0.5 on 2022-06-29 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=30)),
                ('price', models.FloatField(max_length=4)),
                ('image', models.ImageField(upload_to='upload')),
                ('category_FK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='InventCat', to='inventory.itemcategory')),
                ('rating_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratingInvent', to='rating.rating')),
            ],
        ),
    ]
