# Generated by Django 4.0.5 on 2022-07-12 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventory_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='categoryFk',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='ratingFk',
            new_name='rating',
        ),
    ]
