# Generated by Django 4.0.5 on 2022-07-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_categoryfk_inventory_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcategory',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
